version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_CONTAINER_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - arctic-articles-network

networks:
  arctic-articles-network:
    driver: bridge

volumes:
  postgres_data: